### ISSUE TITLE
Russian Bible error

### ISSUE THREAD

**Issue by Andrey5045** [thiagobodruk/bible#13]
When I worked with "Третья книга Царств" (Eng: 1 Kings) I found a missed space:

"чтобы ходить вОфир за золотом", must be
"чтобы ходить в Офир за золотом".

also for some reasons I see only 52 verses in the last chapter, but there must be 53.

I see that in json verse 32 is missing!

32 Начальники колесниц, увидев Иосафата, подумали: "верно это царь Израильский", и поворотили на него, чтобы сразиться с ним. И закричал Иосафат.

**Comment by thiagobodruk** [comment]
Could please describe exactly: version, book and chapter contain the error?

**Comment by Andrey5045** [comment]
I guess my request is self-explanatory. All info you request is mentioned. Thanks
