### ISSUE TITLE
Raw files‘ structure did not contain "book" ，why?

### ISSUE THREAD

**Issue by lhl260** [thiagobodruk/bible#19]
[
	{
	"abbrev" : "abbrev"
	"book" : "name"// not contained in raw files 
	"chapters": 
		[
			["Verse 1", "Verse 2", "Verse 3", "..."],
			["Verse 1", "Verse 2", "Verse 3", "..."],
			["Verse 1", "Verse 2", "Verse 3", "..."]
		]
	}
]

**Comment by thiagobodruk** [comment]
Because the name is included in the file name, feel free to adjust the structure if you need.
