### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by meichthys** [thiagobodruk/bible#25]
It would be nice to have a license on this project.
It would automatically update on this project: https://github.com/meichthys/christian_foss

**Comment by kiki7766** [comment]
I second @meichthys, I would suggest adding a license like MIT, Apache 2.0 or MPL depending your goals!

**Comment by thiagobodruk** [comment]
@meichthys @kiki7766 done!

**Comment by kiki7766** [comment]
Thank you! 🙌🏻
