### ISSUE TITLE
Malformed JSON

### ISSUE THREAD

**Issue by honza** [thiagobodruk/bible#4]
When I tried to load the JSON file of the KJV, I get a parsing error. I wasn't able to find the source of the problem but it fails with multiple tools, e.g. `jq` and `python -mjson.tool`.

Try:

```
$ cat en_kjv.json | python -mjson.tool
```

**Comment by thiagobodruk** [comment]
I'll check it.

**Comment by thiagobodruk** [comment]
I've validated the file using the [Jsonlint CLI tool](https://github.com/zaach/jsonlint) and everything has gone well. If you can give me further details, I'll try to reproduce the issue.

**Comment by thiagobodruk** [comment]
I've tested all the JSON files and everything was OK.

`cat en_kjv.json | jsonlint`

**Comment by honza** [comment]
Did you try this?

```
$ cat en_kjv.json | python -mjson.tool
```

**Comment by thiagobodruk** [comment]
Yes! And it gave me:

```
Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0)
```

It's a basic enconding output issue, not a big deal.

**Comment by thiagobodruk** [comment]
Have you ever tried to implement the JASON using JavaScript or Python?
