### ISSUE TITLE
English KJV Judges Chapter 5 has 32 verses instead of 31

### ISSUE THREAD

**Issue by artsandmetaphysics** [thiagobodruk/bible#9]
In the English KJV bible, in JSON format (i.e., this file https://github.com/thiagobodruk/bible/blob/master/json/en_kjv.json), there is an extra verse at the end of Judges chapter 5.

The extra verse is "And the land had rest forty years."

I checked online in a couple of places, and it appears there should be 31 verses.  E.g., see

https://www.biblegateway.com/passage/?search=Judges+5&version=KJV

**Comment by brandonwkipp** [comment]
Revelation 22:18 😬

**Comment by thiagobodruk** [comment]
@artsandmetaphysics please, feel free to submit a fix.

**Comment by xinthose** [comment]
@thiagobodruk Hello.  The fix is in this PR here already: https://github.com/thiagobodruk/bible/pull/10
